from PIL import Image

# 输入字符串列表
strings = [
# "OOOOOOOOOOOOOOOOOOOOOXXOOOOOOOOO",
# "NOOOOOOOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OPOOOOOOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOPOOOOOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOPOOOOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOPPPOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXPOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOPOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOPOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOPOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOPOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOPOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOPOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOPOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOPOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOPOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOONOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOXXOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOO",
# "OOOOXXXOOOOOOOOOOOOOOOOOOOOOOOOO"
# "OOOXONOOOOOOXXOOOOOO",
# "OOOXOOPOOOOOXXOOOOOO",
# "OOOXOOOPOOOOXXOOOOOO",
# "OOOXOOOOPOOOXXOOOOOO",
# "XXXXOOOOOPOOXXOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOPOOOOOOOOOO",
# "OOOOOOOOOOPPPPOOOOOO",
# "XXXXXXXXXXXXXXPOOOOO",
# "OOOOOOOOOOOOOOPOOOOO",
# "OOOOOOOOOOOOOPOOOOOO",
# "OOOOOOOOOOOPPOOOOOOO",
# "OOOOOOOOOONOOOOOOOOO",
# "OOOOOOOOOOOOOOOOOOOO"

"NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOPOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOPOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOPOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOPOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOPOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOPPPPPPPPPPPOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOXXXOPOOOOOOOOOOOOO",
"OOOOOOOOOOOOOXXXXOOPOOOOOOOOOOOO",
"OOOOOOOOOOOOOXXXXOOOPOOOOOOOOOOO",
"OOOOOOOOOOOOOXXXXOOOOPOOOOOOOOOO",
"OOOOOOOOOOOOOXXXXOOOOOPOOOOOOOOO",
"OOOOOOOOOOOOOXXXXOOOOOOPOOOOOOOO",
"OOOOOOOOOOOOOXXXXOOOOOOOPOOOOOOO",
"OOOOOOOOOOOOOXXXXOOOOOOOOPOOOOOO",
"OOOOOOOOOOOOOXXXXOOOOOOOOOPOOOOO",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOPOOOO",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOPOOO",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOPOO",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOPO",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOOP",
"OOOOOOOOOOOOOXXXXOOOOOOOOOOOOOON"
]

# 将字符转换为不同颜色的值
color_map = {'O': (255, 255, 255),  # 白色
             'P': (255, 0, 0),      # 红色
             'X': (0, 0, 0),        # 黑色
             'N': (0,255,0)}

# 图像大小
width = len(strings[0])
height = len(strings)

# 创建图像对象
img = Image.new('RGB', (width, height), color='white')

# 填充图像数据
for y in range(height):
    for x in range(width):
        img.putpixel((x, y), color_map[strings[y][x]])

# 保存图像
img.save("grid_image.png")